"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { useReducer } from 'react'
import { ComponentReducer, Context, InitialComponentState } from '@/components/reducer'
import { Navbar } from '@/components/pages/NavBar/navbar'
// import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [state, dispatch] = useReducer(
    ComponentReducer,
    InitialComponentState
  );
  return (
    <Context.Provider value={{ dispatch, state }}>
    <html lang="en">
      <body className={inter.className}>
        {/* <AppRouterCacheProvider> */}
        <Navbar></Navbar>
        {children}
        {/* </AppRouterCacheProvider> */}
        </body>
    </html>
    </Context.Provider>
  )
}
